# First, we need to provision 156Mi of space
# for our mongo database.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ben-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
--- 
# Next, we need to attach a Service to expose
# the mongo pods. We will expose port 27017:27017
apiVersion: v1 
kind: Service
metadata:
  name: ben-mongo
spec:
  selector: 
    app: ben-mongo 
  ports:
    - port: 27017
      targetPort: 27017
--- 
# Now we create a stateful set for mongo.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ben-mongo 
spec:
  selector:
    matchLabels:
      app: ben-mongo
  serviceName: ben-mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: ben-mongo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: ben-mongo
          image: mongo:6.0.2-focal
          ports:
            - containerPort: 27017
          volumeMounts:
          - name: storage
            mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 256Mi
